remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: LOL Sec Issues
description: A collection of funny security issues
show_downloads: false
logo: /assets/images/lolsecissues-logo.png